# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

gems: [jekyll-paginate]
paginate: 5
paginate_path: "/page:num/"

# Site settings
title: JavaCasts
email: info@javacasts.net
description: "Java Screencasts"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://javacasts.github.io" # the base hostname & protocol for your site
twitter_username: javacasts
github_username:  javacasts

# Build settings
markdown: kramdown
